### ISSUE TITLE
TypeError: builds.map is not a function

### ISSUE THREAD

**Issue by k13w** [andersonmendess/zeit-test-deploy#1]
Ao clicar em algum item do list ele retorna isso

**TypeError: builds.map is not a function**

{builds.map(build => {

**Comment by andersonmendess** [comment]
já foi corrigido na nossa api: https://github.com/andersonmendess/krakenAPI/commit/4e5e8ac44d6b141c5ad107123ee4dda4890e6527

mas ainda não foi feito o deploy pois o zeit excedeu a cota diaria de builds.
